"""Post review comments to GitHub PRs"""

import requests
from loguru import logger

from bot.cpu_reviewer import ReviewResult
from bot.utils.formatting import (
    clean_multiline_text,
    format_blockquote,
    format_issue_location,
    normalize_whitespace,
)


class CommentPoster:

    def __init__(self, token: str = ""):
        self.token = token or ""
        self.base_url = "https://api.github.com"

    def post_review(
        self,
        repo: str,
        pr_number: int,
        review: ReviewResult,  # type: ignore
        commit_id: str | None = None,
    ) -> bool:
        comment_body = self._format_review_comment(review)

        return self.post_comment(repo, pr_number, comment_body)

    def post_comment(
        self,
        repo: str,
        pr_number: int,
        body: str,
        commit_id: str | None = None,
    ) -> bool:
        if not self.token:
            logger.warning("No GitHub token - cannot post comment")
            logger.info(f"Would post:\n{body}")
            return False

        url = f"{self.base_url}/repos/{repo}/issues/{pr_number}/comments"

        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        payload = {
            "body": body,
        }

        if commit_id:
            payload["commit_id"] = commit_id

        try:
            response = requests.post(url, json=payload, headers=headers)
            response.raise_for_status()

            logger.info(f"Posted review comment to {repo}#{pr_number}")
            return True

        except requests.RequestException as e:
            logger.error(f"Failed to post comment: {e}")
            return False

    def _format_review_comment(self, review: ReviewResult) -> str:  # type: ignore
        lines = [
            "## AI Code Review",
            "",
            f"**Model:** {normalize_whitespace(review.model)} "
            f"({normalize_whitespace(review.review_type)})",
            f"**Quality Score:** {review.score:.1f}/10",
            "",
            "---",
            "",
            "### Summary",
            clean_multiline_text(review.summary),
            "",
        ]

        if review.issues:
            lines.extend([
                "---",
                "",
                "### Issues Found",
                "",
            ])

            severity_icons = {
                "high": ":x:",
                "medium": ":warning:",
                "low": ":information_source:",
            }

            for issue in review.issues:
                icon = severity_icons.get(issue.severity, ":memo:")
                location = format_issue_location(issue.file, issue.line)

                lines.append(f"{icon} {location}")
                lines.append(format_blockquote(issue.message))

                if issue.suggestion:
                    lines.append(
                        format_blockquote(
                            f"_Suggestion: {normalize_whitespace(issue.suggestion)}_"
                        )
                    )

                lines.append("")

        if review.recommendations:
            lines.extend([
                "---",
                "",
                "### Recommendations",
                "",
            ])

            for rec in review.recommendations:
                lines.append(f"- {normalize_whitespace(rec)}")

            lines.append("")

        lines.extend([
            "---",
            "",
            "*Review generated by [deepiri-sorge](https://github.com/deepiri/deepiri-sorge)*",
        ])

        return "\n".join(lines)

    def update_comment(
        self,
        repo: str,
        comment_id: int,
        body: str,
    ) -> bool:
        if not self.token:
            logger.warning("No GitHub token - cannot update comment")
            return False

        url = f"{self.base_url}/repos/{repo}/issues/comments/{comment_id}"

        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

        payload = {"body": body}

        try:
            response = requests.patch(url, json=payload, headers=headers)
            response.raise_for_status()

            logger.info(f"Updated comment {comment_id}")
            return True

        except requests.RequestException as e:
            logger.error(f"Failed to update comment: {e}")
            return False

    def delete_comment(self, repo: str, comment_id: int) -> bool:
        if not self.token:
            logger.warning("No GitHub token - cannot delete comment")
            return False

        url = f"{self.base_url}/repos/{repo}/issues/comments/{comment_id}"

        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

        try:
            response = requests.delete(url, headers=headers)
            response.raise_for_status()

            logger.info(f"Deleted comment {comment_id}")
            return True

        except requests.RequestException as e:
            logger.error(f"Failed to delete comment: {e}")
            return False

    def get_previous_review(
        self,
        repo: str,
        pr_number: int,
    ) -> int | None:
        if not self.token:
            return None

        url = f"{self.base_url}/repos/{repo}/issues/{pr_number}/comments"

        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()

            comments = response.json()

            for comment in comments:
                body = comment.get("body", "")
                if "deepiri-sorge" in body or "AI Code Review" in body:
                    return comment.get("id")

            return None

        except requests.RequestException as e:
            logger.error(f"Failed to get previous reviews: {e}")
            return None
